sudo : required
services:
  -docker

before_install:
  -docker build -t nirajbankar/react-test -f ./client/Dockerfile.dev ./client

script:
  -docker run nirajbankar/react-test npm test -- --coverage



after_success:
  - docker build -t nirajbankar/multi-client ./client
  - docker build -t nirajbankar/multi-nginx ./nginx
  - docker build -t nirajbankar/multi-server ./server
  - docker build -t nirajbankar/multi-worker ./worker

#Login to Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

#take all those images and push them to docker hub
  - docker push nirajbankar/multi-client
  - docker push nirajbankar/multi-nginx
  - docker push nirajbankar/multi-server
  - docker push nirajbankar/multi-worker






